#!/bin/bash
# eidanyosoy
# https://github.com/timothymiller/cloudflare-ddns
# https://github.com/hotio/cloudflareddns
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'cloudflare'
        image: 'hotio/cloudflareddns'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/config:/config'
          - '/etc/localtime:/etc/localtime:ro'
    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'America/New_York'
          UMASK: '002'
          ARGS: ''
          INTERNAL: '300'
          DETECTION_MODE: 'curl-seeip.org'
          LOG_LEVEL: '3'
          APPRISE: ''
          CF_USER: 'your.cf.email@example.com'
          CF_APIKEY: 'your.global.apikey'
          CF_APITOKEN: ''
          CF_APITOKEN_ZONE: ''
          CF_HOSTS: 'plex.yourdomain.com;radarr.yourdomain.com;sonarr.yourdomain.com'
          CF_ZONES: 'yourdomain.com'
          CF_RECORDTYPES: 'A;A;AAAA'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
