#!/bin/bash
#
# Title:      GLANCES
# Author(s):  smashingtags
# URL:
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'glances'
        intport: '61208'
        extport: '61208'
        intport2: '61209'
        extport2: '61209'
        image: 'nicolargo/glances:latest'

    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # EXTRA FUNCTIONS REQUIRED BY THE ROLE #####################################

    - name: 'Create scripts directory for {{pgrole}}'
      file:
        path: /opt/appdata/{{pgrole}}/scripts
        state: directory
        owner: '1000'
        group: '1000'
        mode: '0755'

    # LABELS
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'
          traefik.frontend.headers.SSLProxyHeaders: 'X-Forwarded-Proto: https'
          traefik.frontend.headers.SSLRedirect: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/data:/etc/glances'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/var/run/docker.sock:/var/run/docker.sock:ro'
          - '/opt/appdata/{{pgrole}}/data:/glances/conf'
          #- '/mnt:/mnt'
    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          GLANCES_OPT: '-w'
    # MAIN DEPLOYMENT ##############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
           - '{{ports.stdout}}{{extport}}:{{intport}}'
           - '{{ports.stdout}}{{extport2}}:{{intport2}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        privileged: yes
        #sandbox: no
        state: started
        labels: '{{pg_labels}}'
